# Generated by Django 4.2 on 2023-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('modelo', models.CharField(max_length=30)),
                ('data_compra', models.DateField(max_length=8)),
            ],
        ),
    ]
