# Generated by Django 4.2 on 2023-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('data_aluguel', models.DateField(max_length=8)),
                ('data_entrega', models.DateField(max_length=8)),
                ('diaria', models.CharField(max_length=30)),
            ],
        ),
    ]
